dataloader:
  data_name: cifar100
  batch_size: 256
model:
  model_name: resnet18
optimizer:
  opt_name: sam
  opt_hyperparameter:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.001
    rho: 0.05
trainer:
  epochs: 200
  seed: 42
logging:
  framework_name: wandb
  project_name: sam-cifar100